#!/bin/bash -ex

# This script is meant to be executed inside a working copy of xamarin/xamarin-macios,
# and it will execute the locally installed 'dotnet' executable.
#
# Due to different 'global.json' files in some directories, things won't work
# as expected in every subdirectory. It _should_ work as expected in the
# tests/dotnet directory though, so that should be a safe bet.
#
# Usage: same as 'dotnet'
#

TOPLEVEL=$(git rev-parse --show-superproject-working-tree)
if test -z "$TOPLEVEL"; then
	TOPLEVEL=$(git rev-parse --show-toplevel)
fi

if ! test -f "$TOPLEVEL/tests/test.config"; then
	make test.config -C "$(git rev-parse --show-toplevel)/tests"
fi

DONUT=$(grep ^DOTNET6= "$TOPLEVEL/tests/test.config" | sed 's/^DOTNET6=//')

$DONUT "$@"
