#!/bin/bash -e

# This script is meant to be executed inside a working copy of xamarin/xamarin-macios,
# and it will execute the locally installed 'dotnet' executable.
#
# Usage: same as 'dotnet'
#

TOPLEVEL=$(git rev-parse --show-superproject-working-tree)
if test -z "$TOPLEVEL"; then
	TOPLEVEL=$(git rev-parse --show-toplevel)
fi

if ! test -f "$TOPLEVEL/tests/test.config"; then
	make test.config -C "$(git rev-parse --show-toplevel)/tests"
fi

DONUT=$(grep ^DOTNET= "$TOPLEVEL/tests/test.config" | sed 's/^DOTNET=//')

echo "Using dotnet from: $DONUT"
echo ""

$DONUT "$@"
